version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    command: tail -f /dev/null #uvicorn app:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - /home/fmonzon/Workspace/CurriculumVitae:/app